import type { FilterItem } from '~/model/filter';

export const mockFilters: FilterItem[] = [
  {
    code: 'CATEGORY',
    iblockId: 1,
    name: 'Категория',
    hint: 'Выберите категорию товара',
    displayType: 'F',
    values: [
      {
        htmlValue: 'Смартфоны',
        value: 'Смартфоны',
        urlId: 'smartphones',
        facetValue: 'smartphones',
        count: 5,
        label: 'Смартфоны',
      },
      {
        htmlValue: 'Ноутбуки',
        value: 'Ноутбуки',
        urlId: 'laptops',
        facetValue: 'laptops',
        count: 3,
        label: 'Ноутбуки',
      },
      {
        htmlValue: 'Аудио',
        value: 'Аудио',
        urlId: 'audio',
        facetValue: 'audio',
        count: 4,
        label: 'Аудио',
      },
      {
        htmlValue: 'Планшеты',
        value: 'Планшеты',
        urlId: 'tablets',
        facetValue: 'tablets',
        count: 2,
        label: 'Планшеты',
      },
      {
        htmlValue: 'Игровые консоли',
        value: 'Игровые консоли',
        urlId: 'gaming',
        facetValue: 'gaming',
        count: 2,
        label: 'Игровые консоли',
      },
      {
        htmlValue: 'Периферия',
        value: 'Периферия',
        urlId: 'peripherals',
        facetValue: 'peripherals',
        count: 4,
        label: 'Периферия',
      },
    ],
  },
  {
    code: 'BRAND',
    iblockId: 1,
    name: 'Бренд',
    hint: 'Выберите производителя',
    displayType: 'F',
    values: [
      {
        htmlValue: 'Apple',
        value: 'Apple',
        urlId: 'apple',
        facetValue: 'apple',
        count: 4,
        label: 'Apple',
      },
      {
        htmlValue: 'Samsung',
        value: 'Samsung',
        urlId: 'samsung',
        facetValue: 'samsung',
        count: 3,
        label: 'Samsung',
      },
      {
        htmlValue: 'Sony',
        value: 'Sony',
        urlId: 'sony',
        facetValue: 'sony',
        count: 2,
        label: 'Sony',
      },
      {
        htmlValue: 'LG',
        value: 'LG',
        urlId: 'lg',
        facetValue: 'lg',
        count: 1,
        label: 'LG',
      },
      {
        htmlValue: 'Logitech',
        value: 'Logitech',
        urlId: 'logitech',
        facetValue: 'logitech',
        count: 3,
        label: 'Logitech',
      },
      {
        htmlValue: 'Canon',
        value: 'Canon',
        urlId: 'canon',
        facetValue: 'canon',
        count: 1,
        label: 'Canon',
      },
      {
        htmlValue: 'Razer',
        value: 'Razer',
        urlId: 'razer',
        facetValue: 'razer',
        count: 1,
        label: 'Razer',
      },
      {
        htmlValue: 'Dell',
        value: 'Dell',
        urlId: 'dell',
        facetValue: 'dell',
        count: 1,
        label: 'Dell',
      },
    ],
  },
  {
    code: 'PRICE',
    iblockId: 1,
    name: 'Цена',
    hint: 'Укажите диапазон цен',
    displayType: 'R',
    min: 0,
    max: 300000,
    values: [
      {
        htmlValue: '0',
        value: '0',
        urlId: '0',
        facetValue: '0',
      },
      {
        htmlValue: '300000',
        value: '300000',
        urlId: '300000',
        facetValue: '300000',
      },
    ],
  },
  {
    code: 'AVAILABILITY',
    iblockId: 1,
    name: 'Наличие',
    hint: 'Фильтр по наличию товара',
    displayType: 'F',
    values: [
      {
        htmlValue: 'В наличии',
        value: 'В наличии',
        urlId: 'in-stock',
        facetValue: 'in-stock',
        count: 18,
        label: 'В наличии',
      },
      {
        htmlValue: 'Под заказ',
        value: 'Под заказ',
        urlId: 'pre-order',
        facetValue: 'pre-order',
        count: 2,
        label: 'Под заказ',
      },
    ],
  },
  {
    code: 'RATING',
    iblockId: 1,
    name: 'Рейтинг',
    hint: 'Минимальный рейтинг товара',
    displayType: 'P',
    values: [
      {
        htmlValue: '4.5 и выше',
        value: '4.5',
        urlId: '4.5',
        facetValue: '4.5',
        count: 12,
        label: '4.5 и выше',
      },
      {
        htmlValue: '4.0 и выше',
        value: '4.0',
        urlId: '4.0',
        facetValue: '4.0',
        count: 15,
        label: '4.0 и выше',
      },
      {
        htmlValue: '3.5 и выше',
        value: '3.5',
        urlId: '3.5',
        facetValue: '3.5',
        count: 18,
        label: '3.5 и выше',
      },
      {
        htmlValue: '3.0 и выше',
        value: '3.0',
        urlId: '3.0',
        facetValue: '3.0',
        count: 20,
        label: '3.0 и выше',
      },
    ],
  },
  {
    code: 'DISCOUNT',
    iblockId: 1,
    name: 'Скидка',
    hint: 'Товары со скидкой',
    displayType: 'F',
    values: [
      {
        htmlValue: 'Со скидкой',
        value: 'Со скидкой',
        urlId: 'discounted',
        facetValue: 'discounted',
        count: 8,
        label: 'Со скидкой',
      },
    ],
  },
];
