import type { ProductCard } from '~/model/product';

export const mockProducts: ProductCard[] = [
  {
    id: '1',
    name: 'Смартфон Samsung Galaxy S23 Ultra',
    code: 'SM-G998B',
    price: 89990,
    oldPrice: 109990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '2',
    name: 'Ноутбук Apple MacBook Pro 16" M2',
    code: 'MBP-16-M2',
    price: 249990,
    oldPrice: 279990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '3',
    name: 'Наушники Sony WH-1000XM5',
    code: 'WH-1000XM5',
    price: 34990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '4',
    name: 'Планшет iPad Pro 12.9" M2',
    code: 'IPAD-PRO-129',
    price: 129990,
    oldPrice: 149990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '5',
    name: 'Умные часы Apple Watch Series 9',
    code: 'AW-S9-45',
    price: 49990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '6',
    name: 'Камера Canon EOS R6 Mark II',
    code: 'EOS-R6-M2',
    price: 279990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '7',
    name: 'Игровая консоль PlayStation 5',
    code: 'PS5-STD',
    price: 59990,
    oldPrice: 69990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '8',
    name: 'Телевизор LG OLED C3 55"',
    code: 'OLED55C3',
    price: 149990,
    oldPrice: 179990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '9',
    name: 'Клавиатура Logitech MX Keys',
    code: 'MX-KEYS',
    price: 8990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '10',
    name: 'Мышь Razer DeathAdder V3',
    code: 'DA-V3',
    price: 6990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '11',
    name: 'Монитор Dell UltraSharp U2723DE',
    code: 'U2723DE',
    price: 49990,
    oldPrice: 54990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '12',
    name: 'Внешний SSD Samsung T7 2TB',
    code: 'T7-2TB',
    price: 17990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '13',
    name: 'Беспроводная колонка JBL Charge 5',
    code: 'JBL-CH5',
    price: 12990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '14',
    name: 'Электронная книга Kindle Paperwhite',
    code: 'KPW-11',
    price: 14990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '15',
    name: 'Роутер ASUS RT-AX86U',
    code: 'RT-AX86U',
    price: 19990,
    oldPrice: 22990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '16',
    name: 'Веб-камера Logitech Brio 4K',
    code: 'BRIO-4K',
    price: 14990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '17',
    name: 'Микрофон Blue Yeti X',
    code: 'YETI-X',
    price: 24990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '18',
    name: 'Графический планшет Wacom Intuos Pro',
    code: 'INTUOS-PRO',
    price: 39990,
    oldPrice: 44990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '19',
    name: 'Игровой стул Secretlab Titan',
    code: 'TITAN-2023',
    price: 89990,
    picture: '/assets/img/empty-product.webp',
  },
  {
    id: '20',
    name: 'Блок питания Corsair RM850x',
    code: 'RM850X',
    price: 14990,
    picture: '/assets/img/empty-product.webp',
  },
];
